#!/usr/bin/env node
/**
 * Sync the network reference from PocketBase: every Line and every Station.
 *
 * PocketBase (`POCKETBASE_URL`, default `http://pocketbase.pi`) describes the rail
 * network as it exists; `data/network.ts` is the committed snapshot the app reads.
 * This script copies the first into the second, whole. It is run by hand and is
 * never part of `npm run build`, so a deploy cannot depend on PocketBase being
 * reachable.
 *
 * The snapshot is a TypeScript module rather than JSON on purpose: Cloudflare's
 * Pages Functions bundler cannot parse JSON import attributes (`with { type:
 * "json" }`), and Node refuses a JSON import without one. A generated module
 * loads unchanged in Vite, in Node, and in the Functions bundler.
 *
 * The export is a plain snapshot: every Line and every Station, each Station on
 * its own `sort`, with no filtering. A Station the directory has never used still
 * lands here, because the Contribution form can name any Station on any Line.
 *
 * Each Station carries two link kinds, both stored in PocketBase as relation ids
 * and written here as network codes so the app never sees an id:
 *
 *   interchange — Stations that are one physical station on another Line.
 *   connecting  — Stations joined to a different, walkable station.
 *
 * Usage: `npm run export-network`
 */
import { writeFileSync, rmSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const DATA_PATH = resolve(root, 'data/network.ts');
const RETIRED_JSON_PATH = resolve(root, 'data/network.json');

const BASE_URL = process.env.POCKETBASE_URL ?? 'http://pocketbase.pi';

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

async function fetchAll(collection) {
  const items = [];
  for (let page = 1; ; page++) {
    const url = `${BASE_URL}/api/collections/${collection}/records?perPage=200&page=${page}`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${res.status} ${res.statusText} from ${url}`);
    const body = await res.json();
    items.push(...body.items);
    if (page >= body.totalPages) return items;
  }
}

export function buildNetwork(lines, networkStations) {
  const networkById = new Map(networkStations.map((s) => [s.id, s]));

  const codeOf = (id) => {
    const linked = networkById.get(id);
    if (!linked) {
      throw new Error(`A Station links to ${id}, which is not in train_stations`);
    }
    return linked.code;
  };

  // PocketBase stores the links as relation ids; the snapshot carries codes.
  const codesOf = (codes) => [...(codes ?? [])].map(codeOf).sort();

  return lines.map((line) => {
    const stations = line.stations
      .map((id) => {
        const station = networkById.get(id);
        if (!station) {
          throw new Error(
            `Line ${line.code} lists Station ${id}, which is not in train_stations`,
          );
        }
        if (!station.geoPoint || typeof station.geoPoint.lat !== 'number') {
          throw new Error(`Station ${station.code} has no usable geoPoint`);
        }
        return station;
      })
      .sort((a, b) => a.sort - b.sort)
      .map((s) => ({
        code: s.code,
        name: s.name,
        sort: s.sort,
        // PocketBase stores GeoJSON order (`lon`); the app reads `lng`.
        coordinates: { lat: s.geoPoint.lat, lng: s.geoPoint.lon },
        interchange: codesOf(s.interchange),
        connecting: codesOf(s.connecting),
      }));
    return {
      slug: slugify(line.name),
      code: line.code,
      name: line.name,
      color: line.color,
      stations,
    };
  });
}

async function main() {
  const [lines, networkStations] = await Promise.all([
    fetchAll('train_lines'),
    fetchAll('train_stations'),
  ]);
  console.log(
    `Read ${lines.length} Lines and ${networkStations.length} Stations from ${BASE_URL}`,
  );

  const outLines = buildNetwork(lines, networkStations);

  const next =
    `// Generated by scripts/export-network.mjs from PocketBase.\n` +
    `// Do not edit by hand; run \`npm run export-network\` to refresh it.\n\n` +
    `export type NetworkStation = {\n` +
    `  code: string;\n` +
    `  name: string;\n` +
    `  sort: number;\n` +
    `  coordinates: { lat: number; lng: number };\n` +
    `  /** Stations that are one physical station on another Line, by code. */\n` +
    `  interchange: string[];\n` +
    `  /** Stations joined to a different, walkable station, by code. */\n` +
    `  connecting: string[];\n` +
    `};\n\n` +
    `export type NetworkLine = {\n` +
    `  slug: string;\n` +
    `  code: string;\n` +
    `  name: string;\n` +
    `  color: string;\n` +
    `  stations: NetworkStation[];\n` +
    `};\n\n` +
    `export const lines: NetworkLine[] = ${JSON.stringify(outLines, null, 2)};\n\n` +
    `export default { lines };\n`;
  writeFileSync(DATA_PATH, next);
  if (existsSync(RETIRED_JSON_PATH)) rmSync(RETIRED_JSON_PATH);

  for (const line of outLines) {
    console.log(`  ${line.code} ${line.name}: ${line.stations.length} Stations`);
  }
  const total = outLines.reduce((n, l) => n + l.stations.length, 0);
  console.log(`Wrote ${outLines.length} Lines and ${total} Stations to data/network.ts`);
}

/**
 * Run only when invoked as a script. Importing this module — as the tests do
 * for `buildNetwork` — must not reach PocketBase or rewrite the snapshot.
 */
if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch((e) => {
    console.error(`Export failed: ${e.message}`);
    process.exit(1);
  });
}
