#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Cloudflare's config lives in wrangler.jsonc; the dashboard is the source for
# the values that go into it. wrangler is used only where it is already signed
# in, since its login callback cannot cross machines.
CONFIG="wrangler.jsonc"
PROJECT="${PAGES_PROJECT:-naiktrainjer}"

wrangler() { npx --yes wrangler "$@"; }
wrangler_ready() { wrangler whoami >/dev/null 2>&1; }

# patch_config PERL_PATTERN PERL_REPLACEMENT — rewrites $CONFIG in place.
patch_config() { perl -0pi -e "s/$1/$2/" "$CONFIG"; }

# ask_text VAR "Prompt" [default] — a visible prompt with an editable default.
ask_text() {
  local key="$1" prompt="$2" default="${3:-}" reply
  printf '  %s%s%s [%s]: ' "$BOLD" "$prompt" "$RESET" "$default"
  read -r reply || true
  [[ -n "${reply:-}" ]] || reply="$default"
  printf -v "$key" '%s' "$reply"
}

TOTAL_STAGES=6

banner "Contribute credentials setup"

# ── 1. The Pages project ──────────────────────────────────────────────────
stage "Cloudflare: the Pages project"
say "The Contribute form runs as Cloudflare Pages Functions, so it needs the"
say "Pages project that already serves naiktrainjer.com."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Workers & Pages → the Pages tab."
step "Find the project serving naiktrainjer.com and copy its exact name."
ask_text PROJECT "Pages project name" "$PROJECT"
say "Using Pages project '$PROJECT'."

# ── 2. KV namespace for the rate limiter ──────────────────────────────────
stage "Cloudflare: KV namespace for the rate limiter"
say "The Contribute Function keeps a per-visitor counter in Workers KV. The"
say "namespace id becomes the RATE_LIMIT binding in $CONFIG."
current_id=$(grep -oE '"binding": "RATE_LIMIT", "id": "[^"]*"' "$CONFIG" | grep -oE '[0-9a-f]{32}' | head -n1 || true)
if [[ -n "$current_id" ]]; then
  say "'$CONFIG' already binds RATE_LIMIT to $current_id — leaving it alone."
else
  kv_id=""
  if wrangler_ready; then
    step "wrangler is signed in, so creating the namespace now…"
    kv_out=$(wrangler kv namespace create RATE_LIMIT 2>&1 || true)
    kv_id=$(printf '%s\n' "$kv_out" | grep -oE 'id = "[0-9a-f]{32}"' | grep -oE '[0-9a-f]{32}' | head -n1 || true)
  fi
  if [[ -z "$kv_id" ]]; then
    open_url "https://dash.cloudflare.com/?to=/:account/workers/kv/namespaces"
    step "Select Create instance, name it e.g. naiktrainjer-RATE_LIMIT, then Create."
    step "Open the namespace and copy its ID (a 32-character hex string)."
    ask KV_NAMESPACE_ID "Paste the KV namespace ID:"
    kv_id="$KV_NAMESPACE_ID"
  fi
  if [[ -z "$kv_id" ]]; then
    warn "No namespace id captured. Create one, put its id in $CONFIG, and re-run."
    exit 1
  fi
  say "Namespace id: $kv_id"
  patch_config '("binding": "RATE_LIMIT", "id": ")[^"]*(")' "\${1}$kv_id\${2}"
  say "Wrote it into $CONFIG."
fi

# ── 3. Turnstile widget ───────────────────────────────────────────────────
stage "Cloudflare: Turnstile widget"
say "Turnstile is the bot challenge on the Contribute form. It hands out a public"
say "site key (safe to ship) and a secret key (only the Function ever sees it)."
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Click 'Add widget' (older dashboards call it 'Add site')."
step "Name it 'naiktrainjer'."
step "Hostnames: naiktrainjer.com — add any Pages preview domain you use too."
step "Widget mode: Managed."
step "Create it, then copy the Site Key."
ask TURNSTILE_SITE_KEY "Paste the Turnstile site key:"
step "Now copy the Secret Key."
ask_secret TURNSTILE_SECRET "Paste the Turnstile secret key:"
patch_config '("TURNSTILE_SITE_KEY":\s*")[^"]*(")' "\${1}$TURNSTILE_SITE_KEY\${2}"
say "Wrote the site key into $CONFIG."

# ── 4. GitHub fine-grained token ──────────────────────────────────────────
stage "GitHub: fine-grained token"
say "The Function opens a pull request per Contribution, so it needs a token"
say "limited to this one repository."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: naiktrainjer-contribute."
step "Expiration: pick one, and set a reminder to rotate it."
step "Resource owner: afrieirham. Repository access: Only select repositories → afrieirham/naiktrainjer."
step "Repository permissions: Contents → Read and write, and Pull requests → Read and write."
step "Generate the token and copy it — GitHub shows it once."
ask_secret GITHUB_TOKEN "Paste the fine-grained token:"

# ── 5. Set the Pages secrets ──────────────────────────────────────────────
stage "Cloudflare: set the Pages secrets"
say "The token and the Turnstile secret go on the Pages project as Secret-type"
say "variables, for the Production environment (add Preview too if you use it)."
if wrangler_ready; then
  step "wrangler is signed in, so setting both secrets now…"
  if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    if printf '%s' "$GITHUB_TOKEN" | wrangler pages secret put GITHUB_TOKEN --project-name "$PROJECT"; then
      say "Set GITHUB_TOKEN."
    else
      warn "Could not set GITHUB_TOKEN."
    fi
  fi
  if [[ -n "${TURNSTILE_SECRET:-}" ]]; then
    if printf '%s' "$TURNSTILE_SECRET" | wrangler pages secret put TURNSTILE_SECRET --project-name "$PROJECT"; then
      say "Set TURNSTILE_SECRET."
    else
      warn "Could not set TURNSTILE_SECRET."
    fi
  fi
else
  open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
  step "Workers & Pages → your Pages project '$PROJECT' → Settings → Variables and Secrets."
  step "Add → Type: Secret → Variable name GITHUB_TOKEN → paste the token → Save."
  step "Add → Type: Secret → Variable name TURNSTILE_SECRET → paste the Turnstile secret → Save."
  pause "Press Enter once both secrets are saved."
fi
note "GITHUB_REPO is already a plain var in $CONFIG, so there is nothing to set for it."

# ── 6. Cloudflare Access in front of the admin area ───────────────────────
stage "Cloudflare: protect the admin area with Access"
say "The approve forms and their API are private. One Access application must"
say "cover both paths, or anyone can write to the repository."
open_url "https://one.dash.cloudflare.com/"
step "Access → Applications → Add an application → Self-hosted."
step "Application domain: naiktrainjer.com (add a Pages preview domain if you use one)."
step "Add BOTH paths:"
step "  • /admin*       the admin pages and every deep link"
step "  • /api/admin/*  the reads and writes those pages call"
note "If this plan allows only one path per application, create a second application for the other."
step "Policy: Action Allow, Include → Emails → your maintainer address. No other rules."
step "Leave /api/contribute and /api/config unprotected — the public form must reach them."
pause "Press Enter once the Access application is live."
